### PR TITLE
Adding in support for SafeNet's Luna HSMs.

### PR DESCRIPTION
**Pull request by jpatchell**
Hello, I'm an Engineer that works for Gemalto/Safenet in Canada and I've put together an extension that works with SafeNet's Luna HSMs with the intent to provide a Ruby api to our product for our customers.

Cheers,
Jonathan Patchell

### CODE REVIEW

**Comment by larskanis** [comment]
@jpatchell Sorry for my late response! I'm currently busy with other projects. However I'm very happy to get this PR and this all looks very good! I'll merge it when I've reviewed completely.

Some questions: I would like to build the Luna-gem on my own. Can you provide me library and header files - or is there a download? Is there a simulator to try it out? Or, even better, some hardware :yum: (in fact, 7 years ago I was about to order a Luna HSM, but we then voted for a different vendor)

I read about the renewed standardization process of PKCS#11 (with participation of Safenet). Is this something you're involved?

What do you think about future maintenance - are you willing to provide longer term support for the Luna part (or even the pkcs11 gem)? Or is your task more short term?

**Comment by jpatchell** [comment]
Awesome!

So I've talked to my manager and we will definitely be able to get you remote access to some Luna hardware along with the client and sdk.  I will need you to provide some contact information to get the process underway.

I'm not personally involved with the renewed standardization (you're referring to the OASIS PKCS 11 TC?) process but others in the organization are significant contributors.

In terms of maintenance, I will be able to provide support for the Luna portion.  Basically if issues are coming in through our support channels then I will take responsibility for it.  So if our customers are having issues with the pkcs11 portion, I would likely take a look as well.

By the way, I wanted to mention that I enjoyed learning the code and thought it was really well done!

**Comment by larskanis** [comment]
@jpatchell Is it possible to add ci tests for luna on travis-ci and appveyor? I just updated the test setup, so that both work well on the base pkcs11.gem. I think the question is mostly a legal issue, not a technical.

I was talking to safenet regarding the use of protect server libraries, headers and simulator in 2011, but it came to nothing. This is what is obviously necessary for a ci test. That's why there is non for the pkcs11_protect_server.gem, so far.

I also found recent pkcs11 header files [here](https://www.oasis-open.org/committees/documents.php?wg_abbrev=pkcs11) and updated the bundled files accordingly. I'll have to check what changed.

> By the way, I wanted to mention that I enjoyed learning the code and thought it was really well done!

Thank you! pkcs11 was my very first open source project. My intention was to learn p11. However at work we bypass pkcs11 on most HSMs and run on a direct TCP connection, so that we have full control about client libraries, encryption, authentication and the use of threads.

I could add access permissions for you to this github repository, to ease maintenance. The same on rubygems.org. However it always makes sense to do some kind of coordination before each release. Is this OK for you, or do you have other ideas?

**Comment by jpatchell** [comment]
@larskanis I sent an email to you with my response as well you should have been contacted about getting access to a Luna SA.  Did you receive the emails?

**Comment by larskanis** [comment]
Yes, I got one mail for Luna access and one for a 322MB download. Thank you!

I usually do everything in public, to things related to open source. But the first thing I found in `Luna.zip` is a 24 pages license agreement, with the following paragraphs at the very beginning:

>1.3
Except as otherwise expressly stated in this License, you may not:
a. use, copy, transfer or assign the Software;
[...]
g. load or use any portion of the Software (whether modified or incorporated into or with other software) on or with any machine or system
other than the applicable designated SafeNet hardware or authorized Client.

In my understanding (as a non lawyer and non native English speaker), this prohibits to store the client library, we need to link to, in this github repository. It also prohibits the use of this client library in an open cloud service like travis-ci or appveyor. Am I correct?

**Comment by jpatchell** [comment]
@larskanis Yes, we wouldn't be allowed to store the client library, header files or any part of the client installer in any public or open locations.  Is there someway that travis-ci or appveyor can be configured so that those assets are kept private?

**Comment by larskanis** [comment]
If I remember correctly, both services allow to store text information private to the account. This is usually for something like password or keys. So we could store the URL and/or password into this space, and download the files for each test run. In theory the download link from the mail could be used, in this way, but the file is huge and the link will probably expire sometimes. I don't have any private space on github, but I believe bitbucket provides one free private repository.

Am I allowed to store the client libraries on a private bitbucket repository and to use these in a public appveyor and travis-ci test environment? These environments don't allow any downloads of data used in the tests, but everyone can look at the console outputs.

**Comment by jpatchell** [comment]
So I've asked and it is okay for you to put the library/header files that are needed in a private bitbucket account given that it can only be accessed from within the appveyor or travis-ci test environment and is not accessible publicly.  Any information that would allow access to the bitbucket account would also have to be kept private.  

Also, who would have access to the bitbucket/appveyor/travis-ci accounts?

**Comment by jpatchell** [comment]
Hi Lars,
How's it going?  Have you made any progress setting up the ci environments?  Have you been able to do any testing against the eLab HSM?  I was wondering what the timelines would look like in order to get the luna gem onto rubygems.org.

**Pull request merged**
